# Generated by Django 5.0.4 on 2024-04-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAdmin',
            fields=[
                ('email', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('tenure_start', models.DateField()),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'database_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseClub',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'database_club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseCoach',
            fields=[
                ('email', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('tenure_start', models.DateField()),
                ('contract_start', models.DateField()),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'database_coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseCompetition',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sanctioned', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'database_competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseCompetitioncoachdelegations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'database_competitioncoachdelegations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseCompetitionswimmersattending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'database_competitionswimmersattending',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField()),
                ('final_time', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'database_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('stroke', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'database_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseEventrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField()),
                ('final_time_seconds', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('stroke', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'database_eventrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('monthly_fee', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'database_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseGroupcoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'database_groupcoaches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseGrouppractices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'database_grouppractices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseSwimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'database_swimmer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseSwimmergroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'database_swimmergroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
